version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${DOMAIN_NAME}
      VIKUNJA_SERVICE_JWTSECRET: ${JWTSECRET}
      VIKUNJA_DATABASE_PATH: /db/vikunja.db

      VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: 1

      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_FORCESSL: 1
      VIKUNJA_MAILER_HOST: ${MAILER_HOST}
      VIKUNJA_MAILER_PORT: 465
      VIKUNJA_MAILER_USERNAME: ${MAILER_USERNAME}
      VIKUNJA_MAILER_PASSWORD: ${MAILER_PWD}

    volumes: 
      - ./files:/app/vikunja/files
    networks:
      - proxy
      - default
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.vikunja.entrypoints=web"
      - "traefik.http.routers.vikunja.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.vikunja.middlewares=secureHeaders@file"

        ## HTTP Routers
      - "traefik.http.routers.vikunja-secure.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.vikunja-secure.entrypoints=websecure"
        #      - "traefik.http.routers.vikunja-secure.service=vikunja"
      - "traefik.http.routers.vikunja-secure.tls.certResolver=letsencrypt"

networks:
  proxy:
    name: proxy
    external: true