version: '3.8'

services:
  vikunja:
    image: vikunja/vikunja
    hostname: vikunja
    container_name: vikunja__vikunja
    restart: unless-stopped

    environment:
      VIKUNJA_CORS_ENABLE: true
      VIKUNJA_SERVICE_JWTSECRET: super-secure-random-secret
      VIKUNJA_SERVICE_PUBLICURL: https://do-vikunja-v0a5.onrender.com
      VIKUNJA_DATABASE_PATH: /db/vikunja.db

    volumes:
      - type: volume
        source: vikunja_files
        target: /app/vikunja/files

    expose:
      - 3456

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      - outband

volumes:
  vikunja_files:
    name: vikunja__vikunja_files

networks:
  outband:
    name: vikunja__outband