services:
  vikunja:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIKUNJA_SERVICE_JWTSECRET
      - VIKUNJA_DATABASE_PATH
      - SERVICE_FQDN_VIKUNJA
      - SERVICE_PASSWORD_JWTSECRET
      - 'TIMEZONE=${TIMEZONE-CA}'
      - 'SMTP_HOST=${SMTP_HOST-smtp.smtp2go.com}'
      - 'SMTP_PORT=${SMTP_PORT-2525}'
      - SMTP_USER
      - SMTP_PASSWORD
      - 'SMTP_AUTHTYPE=${SMTP_AUTHTYPE-plain}'
      - 'SMTP_FROMEMAIL=${SMTP_FROMEMAIL-vikunja@mail.aquati.cat}'
      - TODOIST_CLIENTID
      - TODOIST_CLIENTSECRET
      - 'METRICS_USERNAME=${METRICS_USERNAME-user}'
      - METRICS_PASSWORD
    volumes:
      - 'vikunja-data:/opt/vikunja/'
      - ./files:/app/vikunja/files
      - ./db:/db
    ports:
      - '3456:3456'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3456']
        
volumes:
  vikunja-data:
